[build]
  command = "rm -rf node_modules package-lock.json && npm install --include=dev && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22.17.0"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200